logging:
  Level:
    com/mongoAtlas/mongoAtlas: TRACE
  file:
    name: src/main/resources/logs/mongoTemplate-logs.log
  logback:
    rollingpolicy:
      file-name-pattern: mongoTemplate-logs-%d{yyyy-MM-dd}. %i.log
      max-file-size: 5MB
      total-size-cap: 1GB
      max-history: 30